### ISSUE TITLE
S3 Buckets should require requests to use Secure Socket Layer

### ISSUE THREAD

**Issue by chadkluck** [chadkluck/serverless-deploy-pipeline-atlantis#2]
Add a policy to the S3 Artifact Bucket Policy `S3ArtifactBucketPolicy` in the Deploy CloudFormation template for the xxxxxx-deploy bucket.

This is already in the template but is commented out. The statement below is updated. Also, there is a statement that allows insecure transport as a conditional. remove it.

```yaml
  S3ArtifactBucketPolicy:
    
#       [.......]

        Statement:
              - Sid: "DenyNonSecureTransportAccess"
                Effect: Deny
                Principal: "*"
                Action: "s3:*"
                Resource:
                  - !Sub 'arn:aws:s3:::${CodePipelineArtifactStoreBucket}'
                  - !Sub 'arn:aws:s3:::${CodePipelineArtifactStoreBucket}/*'
                Condition:
                  Bool:
                    "aws:SecureTransport": false
```
