### ISSUE TITLE
Add permissions for CodeBuild to sync objects to S3 (such as deploying static assets) in pipeline

### ISSUE THREAD

**Issue by chadkluck** [chadkluck/serverless-deploy-pipeline-atlantis#6]
When deploying applications that have static assets, it is typical to do a build and s3 sync during the CodeBuild phase of the Pipeline.

A permissions set for the CodeBuild Service Role should restrict s3 sync capabilities to just buckets and paths designated for the application:

```yaml

          # We have 4 permissions sets that will allow us to copy objects (such as static assets) over to S3.

          - Sid: "AllowListBuckets"
            Effect: Allow
            Action:
            - s3:ListBucket
            Resource:
            - !Sub "arn:${AWS::Partition}:s3:::*"

          # General buckets for many application projects with paths devoted to applications
          - Sid: CopyAssetsToS3DuringBuildByPath
            Action:
            - s3:PutObject
            - s3:Get*
            - s3:List*
            - s3:DeleteObject
            Effect: Allow
            Resource:
            - !Sub "arn:${AWS::Partition}:s3:::*/${Prefix}-${ProjectId}/${StageId}/*"
            - !Sub "arn:${AWS::Partition}:s3:::*/${Prefix}-${ProjectId}-${StageId}/*"
            - !Sub "arn:${AWS::Partition}:s3:::*/${Prefix}/${ProjectId}/${StageId}/*"

          # A bucket devoted to the application project shared among all deployments of the application
          - Sid: CopyAssetsToS3DuringBuildByBucketApplicationTag
            Action:
            - s3:PutObject
            - s3:Get*
            - s3:List*
            - s3:DeleteObject
            Effect: Allow
            Resource: !Join
            - ""
            - - !Sub "arn:${AWS::Partition}:s3:::"
              - !If [UseS3BucketNameOrgPrefix, !Sub "${S3BucketNameOrgPrefix}-", "" ]
              - !Sub "${Prefix}-${ProjectId}-*/${StageId}/*"

          # A bucket devoted to the specific application deployment
          - Sid: CopyAssetsToS3DuringBuildByBucketApplicationDeploymentTag
            Action:
            - s3:PutObject
            - s3:Get*
            - s3:List*
            - s3:DeleteObject
            Effect: Allow
            Resource: !Join
            - ""
            - - !Sub "arn:${AWS::Partition}:s3:::"
              - !If [UseS3BucketNameOrgPrefix, !Sub "${S3BucketNameOrgPrefix}-", "" ]
              - !Sub "${Prefix}-${ProjectId}-${StageId}-*/*"
```
